// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMD--PLaTvcQwE4kqQ90VgHQHlUGHk8YU',
    appId: '1:321404603003:web:e54d7b9febe794df45b0de',
    messagingSenderId: '321404603003',
    projectId: 'naqel-system',
    authDomain: 'naqel-system.firebaseapp.com',
    storageBucket: 'naqel-system.firebasestorage.app',
    measurementId: 'G-ZWZNKS18VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWdI62XFivWIFNSZIk63HIAFxGoVESaE',
    appId: '1:321404603003:android:1a56eadf50c2f6c345b0de',
    messagingSenderId: '321404603003',
    projectId: 'naqel-system',
    storageBucket: 'naqel-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCFzGGEmZ5PUMPGz18ZaVZf-niMRws0G0',
    appId: '1:321404603003:ios:8e2102c49f7629db45b0de',
    messagingSenderId: '321404603003',
    projectId: 'naqel-system',
    storageBucket: 'naqel-system.firebasestorage.app',
    iosClientId: '321404603003-isjch5sjv2dqll6q4rpce2kf81i66k2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.naqel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMD--PLaTvcQwE4kqQ90VgHQHlUGHk8YU',
    appId: '1:321404603003:web:5a4c84beb732991d45b0de',
    messagingSenderId: '321404603003',
    projectId: 'naqel-system',
    authDomain: 'naqel-system.firebaseapp.com',
    storageBucket: 'naqel-system.firebasestorage.app',
    measurementId: 'G-6L8R1B13LN',
  );
}
