// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5OVnADB0vosMUE8XWIlXDR_HkhWGWf9A',
    appId: '1:419283776231:web:fae75aeef0173bd164e842',
    messagingSenderId: '419283776231',
    projectId: 'naqel-a9ec0',
    authDomain: 'naqel-a9ec0.firebaseapp.com',
    storageBucket: 'naqel-a9ec0.firebasestorage.app',
    measurementId: 'G-6D8BYF1CV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPvkAhPttDY9KW4kI43Ct6PYtpnuPYa98',
    appId: '1:419283776231:android:05f716c61c2a82b264e842',
    messagingSenderId: '419283776231',
    projectId: 'naqel-a9ec0',
    storageBucket: 'naqel-a9ec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpDOaPtKC4DDk3kXLzIhA0M-1S91RaTjY',
    appId: '1:419283776231:ios:38accf4ee949eecd64e842',
    messagingSenderId: '419283776231',
    projectId: 'naqel-a9ec0',
    storageBucket: 'naqel-a9ec0.firebasestorage.app',
    iosBundleId: 'com.example.naqel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpDOaPtKC4DDk3kXLzIhA0M-1S91RaTjY',
    appId: '1:419283776231:ios:38accf4ee949eecd64e842',
    messagingSenderId: '419283776231',
    projectId: 'naqel-a9ec0',
    storageBucket: 'naqel-a9ec0.firebasestorage.app',
    iosBundleId: 'com.example.naqel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5OVnADB0vosMUE8XWIlXDR_HkhWGWf9A',
    appId: '1:419283776231:web:7916f52297851cb764e842',
    messagingSenderId: '419283776231',
    projectId: 'naqel-a9ec0',
    authDomain: 'naqel-a9ec0.firebaseapp.com',
    storageBucket: 'naqel-a9ec0.firebasestorage.app',
    measurementId: 'G-VEBPG6F1LH',
  );
}
